### ISSUE TITLE
[META] Tekstianalyysi

### ISSUE THREAD

**Issue by isoteemu** [Agora-Analytica/prototyyppi#34]
- [x] Jokaisen dataluokan tulee toteuttaa ``text_answers()`` -metodi, joka palauttaa dataframesta tekstimuotoiset sarakkeet. #33
- [x] Muuta links datarakennetta ilmaisemaan sisällöllisiä teemoja
- [x] Esitä teemat graphissa.

**Comment by isoteemu** [comment]
Proof of concept käyttäen Latent Dirichlet Allocation -metodia:  4600ff9

**Comment by isoteemu** [comment]
Feature complete.
